//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beer()
        {
            this.BeerIngredient = new HashSet<BeerIngredient>();
            this.OrderBeer = new HashSet<OrderBeer>();
            this.ProductionProcess = new HashSet<ProductionProcess>();
        }
    
        public int BeerID { get; set; }
        public string Name { get; set; }
        public int BeerTypeID { get; set; }
        public int ManufacturerID { get; set; }
        public Nullable<decimal> ABV { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    
        public virtual BeerType BeerType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeerIngredient> BeerIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBeer> OrderBeer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProcess> ProductionProcess { get; set; }
    }
}
