//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBeer
    {
        public int OrderID { get; set; }
        public int BeerID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
    
        public virtual Beer Beer { get; set; }
        public virtual Order Order { get; set; }
    }
}
